CONFIG_POLL=y
CONFIG_CAN=y
CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_PWM=y
CONFIG_CAN_INIT_PRIORITY=80

CONFIG_SHELL=y
CONFIG_CAN_SHELL=y
CONFIG_DEVICE_SHELL=y

CONFIG_GPIO=y
CONFIG_STATS=y
CONFIG_STATS_NAMES=y
CONFIG_STATS_SHELL=y
CONFIG_CAN_STATS=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_PRINTK=y

# Reasonable main stack
CONFIG_MAIN_STACK_SIZE=2048