CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_UART=y
CONFIG_PRINTK=y
CONFIG_UART_ASYNC_API=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_MODE_OVERFLOW=y

CONFIG_APP_VOLTAGE_MONITORING=y
CONFIG_APP_TEMPERATURE_MONITORING=y
CONFIG_APP_CURRENT_MONITORING=y
CONFIG_APP_FAULT_MONITORING=y
CONFIG_APP_CELL_BALANCING=y

CONFIG_APP_DEBUG_PRINTS=y
CONFIG_APP_DEBUG_VOLTAGES=y
CONFIG_APP_DEBUG_TEMPERATURES=y
CONFIG_APP_DEBUG_CURRENT=y
CONFIG_APP_DEBUG_FAULTS=y
CONFIG_APP_DEBUG_BALANCING=y
